{% set name = "carto-auth" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1a90c0f032c30e0b4af19f0f9b8e382460e920a4d93c92cfa5a30bfe28c93a4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - carto_auth

about:
  home: https://github.com/cartodb/carto-auth
  summary: Python library to authenticate with CARTO
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/CartoDB/carto-auth/tree/master/docs
  dev_url: https://github.com/cartodb/carto-auth

extra:
  recipe-maintainers:
    - Jesus89
